apiVersion: v1
kind: Pod
metadata:
  name: pod-host-path
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-val
          mountPath: /data
  volumes:
    - name: host-val
      hostPath:
        path: /
