---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-secret-reader-1
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-secret-manager-1
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-viewer-1
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-1
  namespace: default
