apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHostPath
metadata:
  name: constraint-hostpath-volume
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - audit-zone