apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPrivileged
metadata:
  name: constraint-no-privileged-pod
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - audit-zone
